### PR TITLE
Added justyy bot

### PR DESCRIPTION
**Pull request by codename-littleboy**
justyy is a curation trail by some chinese users. https://steemit.com/@justyy/transfers shows it has links to a lot of such users and it votes on them as well.

### CODE REVIEW

**Comment by diegopucci** [comment]
justyy just got in contact with me today. Did not seem to be a bot at all

**Comment by DoctorLai** [comment]
Thanks! I am not a bot... come on. those transfer records just show that I  sent them daily interests...

**Comment by DoctorLai** [comment]
do you classify users that use automatic voting services such as steemvoter.com as 'bots'?   there is no way to know that and make a list for that, for sure.

**Comment by DoctorLai** [comment]
Did I pass Turing test?  :)

**Comment by mooncryption** [comment]
Hmm... I don't know, _are_ you a bot? 🤖 

Just kidding, `@justyy` doesn't seem to be a bot, instead looks like he's running a kind of investment service where users are paid dividends.

**Comment by codename-littleboy** [comment]
@mooncryption he does appear to be biased and voting on specific users a lot more. And yes, those who use steemvoter are added.

**Comment by DoctorLai** [comment]
@codename-littleboy   for the record, I don't use steemvoter.  and yes, I only read Chinese posts and vote for quality chinese posts, is that a bias? Everyone has his/her following list, is that a bias?

**Pull request closed without merging**
