### PR TITLE
Force Newlines in Env Section of Readme

### PR DESCRIPTION
**Pull request by caleblogan**
This improves the readability of the env variables in the readme.

### CODE REVIEW

**Comment by wehmoen** [comment]
image
I dont think that this changes anything. Therfore I'm going to close this pull request

**Comment by caleblogan** [comment]
I thought it may help with readability having each env variable on a new line. The 2 spaces force a newline. Its not a big deal, just stuck out during dev setup.
envutopian

**Comment by wehmoen** [comment]
I checked this and there is already one var per line

**Comment by caleblogan** [comment]
It may be a platform issue. I checked on windows and android, chrome and firefox and it looks like the image I posted. Also different markdown renderers don't render newlines the same.

**Comment by wehmoen** [comment]
#Closed

**Pull request closed without merging**
